export default [
    {
        id: 0,
        format: 'audio/mpeg',
        extension: "mp3",
        test: "",
        supported: false,
    },
    {
        id: 1,
        format: 'audio/wav; codecs="1"',
        extension: "wav",
        test: "",
        supported: false,
    },
    {
        id: 2,
        format: 'audio/wav; codecs="3"',
        extension: "wav",
        test: "",
        supported: false,
    },
    {
        id: 3,
        format: 'audio/ogg; codecs="vorbis"',
        extension: "ogg",
        test: "",
        supported: false,
    },
    {
        id: 4,
        format: 'audio/ogg; codecs="opus"',
        extension: "ogg",
        test: "",
        supported: false,
    },
    {
        id: 5,
        format: 'audio/aac',
        extension: "aac",
        test: "",
        supported: false,
    },
    {
        id: 6,
        format: 'audio/flac',
        extension: "flac",
        test: "",
        supported: false,
    },
    {
        id: 7,
        format: 'audio/opus',
        extension: "opus",
        test: "",
        supported: false,
    },
];
