<select class="df" id="s0">
    <option value="0">English (United States)</option>
    <option value="1">English (Great Britain)</option>
    <option value="2">English (Canada)</option>
    <option value="4">English (Australia)</option>
    <option value="5">English (New Zealand)</option>
    <option value="6">English (Ireland)</option>
    <option value="7">English (India)</option>
    <option value="8">Deutsch (Hochdeutsch)</option>
    <option value="9">Dutch (Nederlands)</option>
    <option value="10">Українська</option>
    <option value="11">Hebrew (עברית)</option>
    <option value="12">Polski</option>
    <option value="13">日本語 (Nihongo, Japanese)</option>
    <option value="14">한국어 (Hangugeo, Korean)</option>
    <option value="15">Français</option>
    <option value="16">Italiano</option>
    <option value="17">Ελληνικά (Greek)</option>
    <option value="18">Čeština (Czech)</option>
    <option value="19">Slovenščina (Slovenian)</option>
    <option value="20">Slovenský Jazyk (Slovak)</option>
    <option value="21">Hrvatski (Croatian)</option>
    <option value="22">Bosanski (Bosnian)</option>
    <option value="23">Crnogorski (Montenegrin)</option>
    <option value="24">Македонски (Macedonian)</option>
    <option value="25">Shqip (Albanian)</option>
    <option value="26">Malti (Maltese)</option>
    <option value="27">Lëtzebuergesch (Luxembourgish)</option>
    <option value="28">Gaeilge (Irish)</option>
    <option value="29">Português (Brasil)</option>
    <option value="30">Português (Portugal)</option>
    <option value="31">Español (España)</option>
    <option value="32">Español (México, Latinoamérica)</option>
    <option value="33">Español (Argentina)</option>
    <option value="34">Íslenska</option>
    <option value="35">Kalaallisut (Greenlandic)</option>
    <option value="36">Norsk (Bokmål)</option>
    <option value="37">Norsk (Nynorsk)</option>
    <option value="38">Svenska</option>
    <option value="39">Suomi</option>
    <option value="40">Dansk (Danish)</option>
    <option value="41">Føroyskt (Faroese)</option>
    <option value="42">Беларуская</option>
    <option value="43">Русский</option>
    <option value="44">Hindi (हिन्दी)</option>
    <option value="45">Türkçe (Turkish)</option>
    <option value="46">Eesti Keel (Estonian)</option>
    <option value="47">Lietuvių Kalba (Lithuanian)</option>
    <option value="48">Latviešu Valoda (Latvian)</option>
</select>